root: true
env:
  browser: true
  es2020: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended

ignorePatterns:
  - dist
  - .eslintrc.cjs

overrides: []

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'
  - react-refresh

rules:
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
    
  react/react-in-jsx-scope: off
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-unused-vars': warn

  no-multiple-empty-lines:
    - error
    - max: 1
  semi:
    - error
    - never

  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true

  indent:
    - error
    - 2
    - SwitchCase: 1
      
  object-curly-newline:
    - error
    - multiline: true
      minProperties: 2

  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: false

  object-curly-spacing:
    - error
    - always

  comma-spacing:
    - error
    - before: false
      after: true

  comma-dangle:
    - error
    - always-multiline

  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict

  space-infix-ops:
    - error
    - int32Hint: false
    
  jsx-quotes:
    - error
    - prefer-double

  react/jsx-tag-spacing:
    - error
    - closingSlash: 'never'
      beforeSelfClosing: 'always'
      afterOpening: 'never'
      beforeClosing: 'never'

  react/jsx-props-no-multi-spaces:
    - error

  react/jsx-closing-bracket-location:
    - error
    - location: 'tag-aligned'

  react/jsx-first-prop-new-line:
    - error
    - multiline

  react/jsx-max-props-per-line:
    - error
    - maximum: 1
  react/jsx-indent:
    - error
    - 2

  react/jsx-indent-props:
    - error
    - 2

  react/jsx-closing-tag-location:
    - error
    - location: 'tag-aligned'

  react/jsx-one-expression-per-line:
    - error
    - allow: single-child

  no-trailing-spaces:
    - error
    - skipBlankLines: false